In [62]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,roc_curve

In [179]:
from sklearn.ensemble import BaggingClassifier,RandomForestClassifier,AdaBoostClassifier,VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [64]:
import warnings
warnings.filterwarnings('ignore')

In [80]:
q1=pd.read_csv('Company_data.csv')

In [81]:
q1.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No

In [82]:
from sklearn import preprocessing

In [83]:
le = preprocessing.LabelEncoder()

In [84]:
q1["ShelveLoc"]=le.fit_transform(q1["ShelveLoc"])
q1["Urban"]=le.fit_transform(q1["Urban"])
q1["US"]=le.fit_transform(q1["US"])

In [85]:
q1=q1.assign(Sale=pd.cut(q1['Sales'], 
                               bins=[ 0, 4, 9,15], 
                               labels=['Low', 'Medium', 'High']))

In [86]:
q1.head(10)

Sales  CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
0   9.50        138      73           11         276    120          0   42   
1  11.22        111      48           16         260     83          1   65   
2  10.06        113      35           10         269     80          2   59   
3   7.40        117     100            4         466     97          2   55   
4   4.15        141      64            3         340    128          0   38   
5  10.81        124     113           13         501     72          0   78   
6   6.63        115     105            0          45    108          2   71   
7  11.85        136      81           15         425    120          1   67   
8   6.54        132     110            0         108    124          2   76   
9   4.69        132     113            0         131    124          2   76   

   Education  Urban  US    Sale  
0         17      1   1    High  
1         10      1   1    High  
2         12      1   1    High  
3         14      1   1  Medium  
4         13      1   0  Medium  
5         16      0   1    High  
6         15      1   0  Medium  
7         10      1   1    High  
8         10      0   0  Medium  
9         17      0   1  Medium

In [87]:
q1['Sale']=le.fit_transform(q1['Sale'])

In [75]:
q1 = q1['Sale'].fillna('').apply(str)

In [89]:
q1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Sales        400 non-null    float64
 1   CompPrice    400 non-null    int64  
 2   Income       400 non-null    int64  
 3   Advertising  400 non-null    int64  
 4   Population   400 non-null    int64  
 5   Price        400 non-null    int64  
 6   ShelveLoc    400 non-null    int32  
 7   Age          400 non-null    int64  
 8   Education    400 non-null    int64  
 9   Urban        400 non-null    int32  
 10  US           400 non-null    int32  
 11  Sale         400 non-null    int32  
dtypes: float64(1), int32(4), int64(7)
memory usage: 31.4 KB


In [90]:
q1.drop('Sales',axis=1,inplace=True)

In [91]:
x=q1.iloc[:,0:10]
y=q1.iloc[:,-1]

In [92]:
x.head()

CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
0        138      73           11         276    120          0   42   
1        111      48           16         260     83          1   65   
2        113      35           10         269     80          2   59   
3        117     100            4         466     97          2   55   
4        141      64            3         340    128          0   38   

   Education  Urban  US  
0         17      1   1  
1         10      1   1  
2         12      1   1  
3         14      1   1  
4         13      1   0

In [93]:
y.head(10)

0    0
1    0
2    0
3    2
4    2
5    0
6    2
7    0
8    2
9    2
Name: Sale, dtype: int32

In [94]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [95]:
x_train.shape,y_train.shape

((320, 10), (320,))

In [96]:
x_test.shape,y_test.shape

((80, 10), (80,))

In [97]:
base_model=LogisticRegression()

In [98]:
base_model1=DecisionTreeClassifier()

In [99]:
rf_model=RandomForestClassifier(n_estimators=50,max_depth=4,max_features=3)  

In [100]:
rf_model.fit(x_train,y_train)

RandomForestClassifier(max_depth=4, max_features=3, n_estimators=50)

In [101]:
y_pred=rf_model.predict(x_train)

In [102]:
confusion_matrix(y_train,y_pred)

array([[ 54,   0,  32,   0],
       [  0,   0,  28,   0],
       [  1,   0, 203,   0],
       [  1,   0,   1,   0]], dtype=int64)

In [103]:
print(classification_report(y_train,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.63      0.76        86
           1       0.00      0.00      0.00        28
           2       0.77      1.00      0.87       204
           3       0.00      0.00      0.00         2

    accuracy                           0.80       320
   macro avg       0.43      0.41      0.41       320
weighted avg       0.75      0.80      0.76       320



In [104]:
pred=rf_model.predict(x_test)
pred

array([2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0])

In [105]:
confusion_matrix(y_test,pred)

array([[10,  0, 15,  0],
       [ 0,  0,  7,  0],
       [ 5,  0, 42,  0],
       [ 1,  0,  0,  0]], dtype=int64)

In [106]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.62      0.40      0.49        25
           1       0.00      0.00      0.00         7
           2       0.66      0.89      0.76        47
           3       0.00      0.00      0.00         1

    accuracy                           0.65        80
   macro avg       0.32      0.32      0.31        80
weighted avg       0.58      0.65      0.60        80



# Question2 

In [109]:
q2=pd.read_csv('Fraud_check.csv')

In [110]:
q2

Undergrad Marital.Status  Taxable.Income  City.Population  \
0          NO         Single           68833            50047   
1         YES       Divorced           33700           134075   
2          NO        Married           36925           160205   
3         YES         Single           50190           193264   
4          NO        Married           81002            27533   
..        ...            ...             ...              ...   
595       YES       Divorced           76340            39492   
596       YES       Divorced           69967            55369   
597        NO       Divorced           47334           154058   
598       YES        Married           98592           180083   
599        NO       Divorced           96519           158137   

     Work.Experience Urban  
0                 10   YES  
1                 18   YES  
2                 30   YES  
3                 15   YES  
4                 28    NO  
..               ...   ...  
595                7   YES  
596                2   YES  
597                0   YES  
598               17    NO  
599               16    NO  

[600 rows x 6 columns]

In [111]:
q2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Undergrad        600 non-null    object
 1   Marital.Status   600 non-null    object
 2   Taxable.Income   600 non-null    int64 
 3   City.Population  600 non-null    int64 
 4   Work.Experience  600 non-null    int64 
 5   Urban            600 non-null    object
dtypes: int64(3), object(3)
memory usage: 28.2+ KB


In [164]:
DF=pd.Series(q2['Taxable.Income'])
su=[]
for i in DF:
    if i<=30000:
        su.append("risky")
    else:
        su.append('good')
print(su)

['good', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'risky', 'good', 'risky', 'good', 'good', 'good', 'risky', 'good', 'good', 'risky', 'good', 'risky', 'good', 'good', 'good', 'good', 'good', 'good', 'risky', 'good', 'good', 'good', 'good', 'good', 'risky', 'good', 'risky', 'good', 'risky', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'risky', 'good', 'good', 'good', 'good', 'risky', 'good', 'risky', 'good', 'good', 'risky', 'good', 'good', 'risky', 'good', 'good', 'good', 'good', 'good', 'good', 'risky', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'risky', 'good', 'good', 'good', 'good', 'good', 'risky', 'good', 'risky', 'good', 'risky', 'good', 'good', 'good', 'risky', 'risky', 'good', 'risky', 'good', 'risky', 'good', 'good', 'good', 'good', 'good', 'good', 'good', 'risky', 'good', 'good', 'good', 'risky', 'good', 'good', 'good', 'risky', 'good', 'good', 'good', 'risky', 'good', 'good', 'ris

In [166]:
DF2=pd.DataFrame(su)
DF2=pd.concat([DF2,q2],axis=1)
DF2=DF2.rename({0:'o/p'},axis=1)

In [167]:
DF2

o/p  Taxable.Income  population  work  Undergrad_YES  \
0    good           68833       50047    10              0   
1    good           33700      134075    18              1   
2    good           36925      160205    30              0   
3    good           50190      193264    15              1   
4    good           81002       27533    28              0   
..    ...             ...         ...   ...            ...   
595  good           76340       39492     7              1   
596  good           69967       55369     2              1   
597  good           47334      154058     0              0   
598  good           98592      180083    17              1   
599  good           96519      158137    16              0   

     Marital.Status_Married  Marital.Status_Single  Urban_YES  TaxInc_Good  
0                         0                      1          1            1  
1                         0                      0          1            1  
2                         1                      0          1            1  
3                         0                      1          1            1  
4                         1                      0          0            1  
..                      ...                    ...        ...          ...  
595                       0                      0          1            1  
596                       0                      0          1            1  
597                       0                      0          1            1  
598                       1                      0          0            1  
599                       0                      0          0            1  

[600 rows x 9 columns]

In [170]:
labelencoder=LabelEncoder()
DF2.iloc[:,0]=labelencoder.fit_transform(DF2.iloc[:,0])
DF2.iloc[:,1]=labelencoder.fit_transform(DF2.iloc[:,1])
DF2.iloc[:,2]=labelencoder.fit_transform(DF2.iloc[:,2])
DF2.iloc[:,-1]=labelencoder.fit_transform(DF2.iloc[:,-1])

In [171]:
DF2

o/p  Taxable.Income  population  work  Undergrad_YES  \
0      0             387          84    10              0   
1      0             163         398    18              1   
2      0             186         481    30              0   
3      0             272         574    15              1   
4      0             468           4    28              0   
..   ...             ...         ...   ...            ...   
595    0             436          55     7              1   
596    0             395         107     2              1   
597    0             251         459     0              0   
598    0             587         533    17              1   
599    0             569         477    16              0   

     Marital.Status_Married  Marital.Status_Single  Urban_YES  TaxInc_Good  
0                         0                      1          1            1  
1                         0                      0          1            1  
2                         1                      0          1            1  
3                         0                      1          1            1  
4                         1                      0          0            1  
..                      ...                    ...        ...          ...  
595                       0                      0          1            1  
596                       0                      0          1            1  
597                       0                      0          1            1  
598                       1                      0          0            1  
599                       0                      0          0            1  

[600 rows x 9 columns]

In [172]:
DF2=DF2.values

In [173]:
x=DF2[:,1:7]
y=DF2[:,0]

In [180]:
num_trees = 100
max_features = 4
kfold = KFold(n_splits=10)
model = RandomForestClassifier(n_estimators=num_trees, max_features=max_features)
results = cross_val_score(model, x, y, cv=kfold)
print(results.mean())

0.9983333333333334
